<a href="https://colab.research.google.com/github/sibasishsahu68/AML-Lab/blob/main/Experiment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
from scipy.stats import chi2_contingency

# Create the observed frequency table (contingency table)
data = {
    'Buys Protein Powder: Yes': [10, 5],
    'Buys Protein Powder: No': [5, 10]
}
index = ['Like Sports: Yes', 'Like Sports: No']
observed_df = pd.DataFrame(data, index=index)

print("Observed Frequencies (Contingency Table):")
display(observed_df)

# Perform the Chi-Squared Test
chi2, p_value, dof, expected_df = chi2_contingency(observed_df)

print(f"\nChi-squared statistic: {chi2:.3f}")
print(f"P-value: {p_value:.3f}")
print(f"Degrees of Freedom: {dof}")
print("\nExpected Frequencies:")
display(pd.DataFrame(expected_df, index=index, columns=observed_df.columns))

# Interpret the results
alpha = 0.05
tabulated_chi2 = 3.841

print("\n--- Interpretation ---")
print(f"Significance level (alpha): {alpha}")
print(f"Tabulated Chi-squared value (at alpha=0.05, df={dof}): {tabulated_chi2}")

if p_value < alpha:
    print(f"Since the p-value ({p_value:.3f}) is less than alpha ({alpha}), we reject the null hypothesis.")
    print("There is a statistically significant association between liking sports and buying protein powder.")
else:
    print(f"Since the p-value ({p_value:.3f}) is greater than or equal to alpha ({alpha}), we fail to reject the null hypothesis.")
    print("There is no statistically significant association between liking sports and buying protein powder.")

print("\nComparing Chi-squared statistic with Tabulated value:")
if chi2 > tabulated_chi2:
    print(f"Since the calculated Chi-squared statistic ({chi2:.3f}) is greater than the tabulated value ({tabulated_chi2:.3f}), we reject the null hypothesis.")
    print("There is a statistically significant association between liking sports and buying protein powder.")
else:
    print(f"Since the calculated Chi-squared statistic ({chi2:.3f}) is less than or equal to the tabulated value ({tabulated_chi2:.3f}), we fail to reject the null hypothesis.")
    print("There is no statistically significant association between liking sports and buying protein powder.")

Observed Frequencies (Contingency Table):

                  Buys Protein Powder: Yes  Buys Protein Powder: No
Like Sports: Yes                        10                        5
Like Sports: No                          5                       10

Chi-squared statistic: 2.133
P-value: 0.144
Degrees of Freedom: 1

Expected Frequencies:

                  Buys Protein Powder: Yes  Buys Protein Powder: No
Like Sports: Yes                       7.5                      7.5
Like Sports: No                        7.5                      7.5

--- Interpretation ---
Significance level (alpha): 0.05
Tabulated Chi-squared value (at alpha=0.05, df=1): 3.841
Since the p-value (0.144) is greater than or equal to alpha (0.05), we fail to reject the null hypothesis.
There is no statistically significant association between liking sports and buying protein powder.

Comparing Chi-squared statistic with Tabulated value:
Since the calculated Chi-squared statistic (2.133) is less than or equal to the tabulated value (3.841), we fail to reject the null hypothesis.
There is no statistically significant association between liking sports and buying protein powder.

Chi-squared statistic: 2.133
P-value: 0.144
Degrees of Freedom: 1

Expected Frequencies:

                  Buys Protein Powder: Yes  Buys Protein Powder: No
Like Sports: Yes                       7.5                      7.5
Like Sports: No                        7.5                      7.5

--- Interpretation ---
Significance level (alpha): 0.05
Tabulated Chi-squared value (at alpha=0.05, df=1): 3.841
Since the p-value (0.144) is greater than or equal to alpha (0.05), we fail to reject the null hypothesis.
There is no statistically significant association between liking sports and buying protein powder.

Comparing Chi-squared statistic with Tabulated value:
Since the calculated Chi-squared statistic (2.133) is less than or equal to the tabulated value (3.841), we fail to reject the null hypothesis.
There is no statistically significant association between liking sports and buying protein powder.